spring:
  sql:
    init:
      mode: always
  datasource:
    username: sa
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
