

INSERT INTO MPA (MPA_NAME) VALUES('G');
INSERT INTO MPA (MPA_NAME) VALUES('PG');
INSERT INTO MPA (MPA_NAME) VALUES('PG-13');
INSERT INTO MPA (MPA_NAME) VALUES('R');
INSERT INTO MPA (MPA_NAME) VALUES('NC-17');

INSERT INTO GENRE (NAME) VALUES('Комедия');
INSERT INTO GENRE (NAME) VALUES('Драма');
INSERT INTO GENRE (NAME) VALUES('Мультфильм');
INSERT INTO GENRE (NAME) VALUES('Триллер');
INSERT INTO GENRE (NAME) VALUES('Документальный');
INSERT INTO GENRE (NAME) VALUES('Боевик');

