DROP TABLE USER_LIKES_FILM IF EXISTS;
DROP TABLE FILM_GENRE IF EXISTS;
DROP TABLE GENRE IF EXISTS;
DROP TABLE FILM_DIRECTORS IF EXISTS;
DROP TABLE DIRECTOR IF EXISTS;
DROP TABLE FRIEND_LIST IF EXISTS;
DROP TABLE FILMORATE_USER IF EXISTS;
DROP TABLE FILM IF EXISTS;
DROP TABLE MPA IF EXISTS;

CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MPA_NAME CHARACTER VARYING(50),
    CONSTRAINT uc_mpa_name UNIQUE (MPA_NAME)
);

CREATE TABLE IF NOT EXISTS FILM
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(100) not null,
    DESCRIPTION CHARACTER VARYING(200),
    DURATION INTEGER,
    RELEASE_DATE DATE,
    MPA_ID BIGINT not null references MPA(MPA_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FILMORATE_USER
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL CHARACTER VARYING(100),
    LOGIN CHARACTER VARYING(50) not null,
    NAME CHARACTER VARYING(50),
    BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS FRIEND_LIST
(
    USER_ID BIGINT not null references FILMORATE_USER(ID) ON DELETE CASCADE,
    FRIEND_ID BIGINT not null references FILMORATE_USER(ID) ON DELETE CASCADE,
    STATUS_OF_FRIENDSHIP BOOLEAN,
    constraint FRIEND_LIST_PK primary key (USER_ID, FRIEND_ID)
);

CREATE TABLE IF NOT EXISTS GENRE
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(50),
    CONSTRAINT uc_genre_name UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    GENRE_ID BIGINT not null references GENRE(ID) ON DELETE CASCADE,
    FILM_ID BIGINT not null references FILM(ID) ON DELETE CASCADE,
    constraint FILM_GENRE_PK primary key (GENRE_ID, FILM_ID)
);

CREATE TABLE IF NOT EXISTS USER_LIKES_FILM
(
    USER_ID BIGINT not null references FILMORATE_USER ON DELETE CASCADE,
    FILM_ID BIGINT not null references FILM ON DELETE CASCADE,
    constraint USER_LIKES_FILM_PK primary key (USER_ID, FILM_ID)
);

CREATE TABLE IF NOT EXISTS DIRECTOR
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(100) not null
);

CREATE TABLE IF NOT EXISTS FILM_DIRECTORS
(
    FILM_ID BIGINT not null references FILM(ID) ON DELETE CASCADE,
    DIRECTOR_ID BIGINT not null references DIRECTOR(ID) ON DELETE CASCADE,
    constraint FILM_DIRECTORS_PK PRIMARY KEY (FILM_ID, DIRECTOR_ID)
);


